### ISSUE TITLE
Typo? 'ghostwheel' vs. 'guardrails'

### ISSUE THREAD

**Issue by jonathn** [fulcrologic/fulcro-template#19]
Should these 3 mentions of **ghostwheel** actually be **guardrails**?

1) in https://github.com/fulcrologic/fulcro-template/blob/master/package.json#L15
    `"server": "clojure -A:dev -J-Dtrace -J-Dghostwheel.enabled=true",`

2) in https://github.com/fulcrologic/fulcro-template/blob/master/README.adoc
    `clj -A:dev -J-Dtrace -J-Dghostwheel.enabled=true`

3) in the actual `guardrails` repo..
    in https://github.com/fulcrologic/guardrails/blob/d53c48eeca875a336c71cc6084b81e920191d9d7/src/main/com/fulcrologic/guardrails/config.cljc#L33
    `;; `defn`-like macros, you can have Ghostwheel desugar to`

**Comment by awkay** [comment]
thanks
