### ISSUE TITLE
install peer-dependencies: object-assign, scheduler

### ISSUE THREAD

**Issue by milahu** [fulcrologic/fulcro-template#26]
with `pnpm install` i get the errors

> The required JS dependency "object-assign" is not available, it was required by "node_modules/react/cjs/react.production.min.js".
> The required JS dependency "scheduler" is not available, it was required by "node_modules/react-dom/cjs/react-dom.production.min.js".

fixed by

```
pnpm i -D object-assign scheduler@0.20.2
```

because https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html

**Comment by awkay** [comment]
Not sure what you're asking for here. If it's an update to package.json, just send a PR.
