### ISSUE TITLE
index.html for workspaces seems to be missing

### ISSUE THREAD

**Issue by darwin** [fulcrologic/fulcro-template#4]
Just toying with Fulcro. And trying to learn from this template. 

I noticed that workspaces index.html is nowhere to be found after enabling the workspaces build (at least http://localhost:8023/workspaces does not have it).

I fixed it by placing index.html similar into `resources/public/workspaces` dir.
I took [this one](https://github.com/nubank/workspaces/blob/e3137fe13795d0ac3070bc432f6cc2453787d86f/examples/workspaces-shadow-example/resources/public/index.html). And updated the path to the main.js (should be `js/main.js`).

**Comment by awkay** [comment]
It is generated by the server so CSRF protections can be embedded in the page. Perhaps I got the link wrong in teh README

**Comment by awkay** [comment]
https://github.com/fulcrologic/fulcro-template/blob/master/src/main/app/server_components/middleware.clj#L80

**Comment by awkay** [comment]
Updated README
