### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by slifin** [fulcrologic/fulcro-template#7]
Hi this is likely a naive question 

But how do I do hello world in this stack?

I've tried:
`npm install`
`npm run client/main`

Compiling the main build via `http://localhost:9630/dashboard` 
Creating an `index.html` in public/resources pointed to `/js/main/main.js` with div#app

Accessing the page at: `http://localhost:8022/`

**Comment by awkay** [comment]
Please see: 

book.fulcrologic.com/fulcro3
the README
or ask questions on the Clojurians #fulcro Slack channel.
